Repository Cypherock/x1_wallet_firmware, pull requests merged in 2023-06, with the labels that each got.

#308 refactor: Add bitcoin derivation path guard
  apps/btc_app/btc_helpers.c
  apps/btc_app/btc_helpers.h
  apps/btc_app/get_public_key.c
  apps/btc_app/get_xpub.c
  tests/common/util/xpub_verify_tests.c
Labels: enhancement, refactor

#310 refactor: Clean lvgl objs before input scr and remove duplicate comment
  common/interfaces/user_interface/ui_address.c
  common/interfaces/user_interface/ui_confirmation.c
  common/interfaces/user_interface/ui_delay.c
  common/interfaces/user_interface/ui_input_mnemonics.c
  common/interfaces/user_interface/ui_input_text.c
  common/interfaces/user_interface/ui_instruction.c
  common/interfaces/user_interface/ui_joystick_training.c
  common/interfaces/user_interface/ui_list.c
  common/interfaces/user_interface/ui_menu.c
  common/interfaces/user_interface/ui_message.c
  common/interfaces/user_interface/ui_multi_instruction.c
  common/interfaces/user_interface/ui_scroll_page.c
  common/interfaces/user_interface/ui_skip_instruction.c
  common/interfaces/user_interface/ui_text_slideshow.c
Labels: refactor

#311 chore: Fix directory structure of merged flows
  src/card_flows/card_flow_reconstruct_wallet.c
  src/card_operations/card_fetch_share.c
  src/wallet/create_wallet_flow.c
Labels: refactor

#307 refactor(app): Updated pairing flow for separate handling
  apps/manager_app/auth_card.c
  common/interfaces/flash_interface/flash_api.c
  common/interfaces/flash_interface/flash_api.h
  src/app_error.h
  src/card_operations/card_internal.c
  src/card_operations/card_pair.c
  src/card_operations/card_pair.h
  src/card_operations/check_pairing.c
  src/card_operations/check_pairing.h
  src/level_four/core/controller/controller_level_four.h
  src/level_four/core/controller/initial_verify_card_controller.c
  src/level_four/core/controller/verify_card_controller.c
  src/level_four/tap_cards/controller/controller_tap_cards.c
  src/level_four/tap_cards/controller/controller_tap_cards.h
  src/level_three/advanced_settings/controller/advanced_settings_controller.c
Labels: enhancement, refactor

#306 fix(app): Error handling for auth card
  apps/manager_app/auth_card.c
  apps/manager_app/manager_app.h
  src/card_operations/card_return_codes.h
  src/card_operations/card_sign.c
  src/card_operations/card_sign.h
  src/card_operations/card_utils.c
  src/menu/host_interface.c
Labels: enhancement

#314 refactor: Integrate seed recreation flow in btc functions
  apps/btc_app/get_public_key.c
  apps/btc_app/get_xpub.c
Labels: enhancement
