Repository Cypherock/x1_wallet_firmware, pull requests merged in 2023-07, with the labels that each got.

#325 Fix/auth card without pairing
  apps/manager_app/auth_card.c
  common/core/status_api.c
  common/core/status_api.h
  src/card_operations/card_return_codes.h
  src/level_four/tap_cards/controller/controller_tap_cards.h
Labels: bugfix

#334 fix(app): Fix reconstruct flow for passphrase enabled wallet
  src/wallet/reconstruct_seed_flow.c
Labels: bugfix

#330 feat(flow): Update locked wallet state in flash
  common/interfaces/flash_interface/flash_api.c
  common/interfaces/flash_interface/flash_api.h
  src/card_operations/card_fetch_share.c
  src/card_operations/card_utils.c
  src/card_operations/card_utils.h
  src/wallet/wallet_list.c
  src/wallet/wallet_list.h
Labels: enhancement

#338 feat(core): Added old wallet menu
  src/menu/main_menu.c
  src/menu/wallet_menu.c
  src/menu/wallet_menu.h
Labels: enhancement

#344 fix: Remove seed generated message from create new wallet flow
  src/constant_texts.c
  src/constant_texts.h
  src/level_three/add_wallet/tasks/tasks_new_wallet.c
  src/wallet/create_new_wallet_flow.c
Labels: enhancement

#343 refactor: Remove 'CARD_OPERATION_PAIRING_REQUIRED' card error type
  src/card_operations/card_internal.c
  src/card_operations/card_return_codes.h
  src/wallet/reconstruct_seed_flow.c
Labels: enhancement

#341 refactor: Port factory reset into new architecture
  src/constant_texts.c
  src/constant_texts.h
  src/level_four/factory_reset/cyc_factory_reset.c
  src/level_four/factory_reset/cyt_factory_reset.c
  src/menu/settings_menu.c
  src/settings/factory_reset.c
  src/settings/settings_api.h
  src/wallet/wallet_list.c
  src/wallet/wallet_list.h
Labels: feature
